# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a14b7fb157255a1a50b80dd75f4251ec8d35e54135335dd613ac6ab2a2015f333d25ef3622156ce8ee2a945e59bdbacc31ea417abbd6caf6d44acbc2846522

test:
  secret_key_base: 9a0628da10d1e129ba15d3c24dd854d5fcf345f18a21abc9ffc064e216a7be970ca64d35e754eb0d1151c943bb2d09cca822efd61978bfb2c32b98fbe1f25f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
